### ISSUE TITLE
can u share the database sql file 

### ISSUE THREAD

**Issue by shook1337** [pjanicked/ContactViewAPI#7]
i really want this project to build with it

**Comment by pjanicked** [comment]
Hi, Sorry I havent updated the readme for this project.
You may need to download postgresql and pgAdmin/DBeaver first.
Then create a database named ContactViewDb -> Give the connection string in appsettings.json -> and you are good to go!

Let me know if you need any more info

**Comment by shook1337** [comment]
i created the database in pgadmin and now i cant register i have this error: 
![Screenshot_1](https://user-images.githubusercontent.com/73116436/106305948-a2ef3b80-625d-11eb-8a4e-18d9be1e9106.png)

**Comment by pjanicked** [comment]
Hi, have you resolved this?
Else, we can connect over discord?

**Comment by shook1337** [comment]
whats your discord

**Comment by pjanicked** [comment]
pjanicked#6915

**Comment by shook1337** [comment]
added u im (roca)
